/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_gi_gamespy_jni_Transport */

#ifndef _Included_com_sun_gi_gamespy_jni_Transport
#define _Included_com_sun_gi_gamespy_jni_Transport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2Accept
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2Accept
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2CloseAllConnections
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2CloseAllConnections
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2CloseAllConnectionsHard
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2CloseAllConnectionsHard
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2CloseConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2CloseConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2CloseConnectionHard
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2CloseConnectionHard
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2CloseSocket
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2CloseSocket
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2Connect
 * Signature: (JLjava/lang/String;[BII)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2Connect
  (JNIEnv *, jclass, jlong, jstring, jbyteArray, jint, jint);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2CreateSocket
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2CreateSocket
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2Listen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2Listen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2Reject
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2Reject
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2Send
 * Signature: (J[BZ)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2Send
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jboolean);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2Think
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2Think
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_init
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    lastResult
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL Java_com_sun_gi_gamespy_JNITransport_lastResult
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_gi_gamespy_jni_Transport
 * Method:    gt2Ping
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_gi_gamespy_JNITransport_gt2Ping
  (JNIEnv *, jclass, jlong);


#ifdef __cplusplus
}
#endif
#endif
