/* Generated by Together */

package com.sun.gi.server.ostore;


public interface ObjectStore {
    long getTimestamp();
    Transaction newTransaction(long timestamp);
    long lookup(String name);
}
