package com.sun.sgs.kernel.scheduling;

import com.sun.sgs.Quality;
import com.sun.sgs.kernel.Task;

/**
 * The <code>TaskScheduler</code> concurrently runs system-level
 * {@link Task} requests.  <code>Task</code> requests are generated by
 * the infrastructure itself as well as by services on the behalf of
 * the application.  Therefore, the <code>TaskScheduler</code> serves
 * as an entry point for all types of execution in the system.
 *
 *
 * @since 1.0
 * @author James Megquier
 * @author Seth Proctor
 * @authod David Jurgens
 */
public interface TaskScheduler {

    /**
     * Queues a task to run when the resources are available.  The
     * time of execution is dependent the implementation.
     *
     * @param task the <code>Task</code> to run
     *
     * @see PriorityProvider#getPriority(Task)
     */
    public void queueTask(Task task);


}
