/* Generated by Together */

package com.sun.gi.objectstore;


public interface ObjectStore {
  public static final long INVALID_ID = Long.MIN_VALUE;
  public Transaction newTransaction(long appID, ClassLoader loader);

  public void clear();

  public long getTimestampTimeout();

  public long getObjectID();
  
  public OStoreMetaData peekMetaData(Transaction trans);

  public OStoreMetaData lockMetaData(Transaction trans);

}
