#!/bin/sh

# 
# Copyright (c) 2001, Sun Microsystems Laboratories 
# All rights reserved. 
# 
# Redistribution and use in source and binary forms, 
# with or without modification, are permitted provided 
# that the following conditions are met: 
# 
#     Redistributions of source code must retain the 
#     above copyright notice, this list of conditions 
#     and the following disclaimer. 
#             
#     Redistributions in binary form must reproduce 
#     the above copyright notice, this list of conditions 
#     and the following disclaimer in the documentation 
#     and/or other materials provided with the distribution. 
#             
#     Neither the name of Sun Microsystems, Inc. nor 
#     the names of its contributors may be used to endorse 
#     or promote products derived from this software without 
#     specific prior written permission. 
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND 
# CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, 
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY 
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
# THE POSSIBILITY OF SUCH DAMAGE. 
#

#
# Script to launch a JRMS user application.

jdkfcs=/net/labeast.east/files3/tools/jdk1.2fcs
exactvm=/net/bcn.east/files3/home/Solaris_JDK_1.2.1_03
jrms_classes=/home/jrms/version1.0/classes

#
# Use ExactVM if we can
#

outputdir=/home/$USER/test/`uname -n`

if [ ! -d "$outputdir" ]; then
	mkdir -p $outputdir
fi

uname -r | egrep 5.[78] > /dev/null 2>&1
status=$?

if [ "$status" = "0" ]; then
    $exactvm/bin/java -version > /dev/null 2>&1
    status=$?
fi

if [ "$status" = "0" ]; then

    echo Starting JRMS application using ExactVM.
    java=$exactvm/bin/java
    vm=$exactvm

else

    echo Starting JRMS application using jdk1.2fcs.
    java=$jdkfcs/bin/java
    vm=$jdkfcs

fi

CLASSPATH=.:$vm/lib:$jdkfcs/jce12-rc1-dom/lib/jce12-rc1-dom.jar:$jrms_classes; export CLASSPATH
#echo CLASSPATH=.:$vm/lib:$jdkfcs/jce12-rc1-dom/lib/jce12-rc1-dom.jar:$jrms_classes; export CLASSPATH

$java com.sun.multicast.reliable.applications.mctest.MCTest -c -m 8 -r 1000 -R 200000 -C 2 -o $outputdir/MCTestReceive.txt $* >> $outputdir/mrtest.log 2>&1 
